/**
* Community Quiz
* This is the server for my community quiz game
*
* OpenAPI spec version: 1.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package hu.bme.communityQuiz.server.network

import io.ktor.application.ApplicationCall
import io.ktor.http.HttpMethod
import io.ktor.locations.*
import io.ktor.routing.Route
import io.ktor.routing.method
import io.ktor.util.pipeline.*


// NOTE: ktor-location@0.9.0 is missing extension for Route.delete. This includes it.
inline fun <reified T : Any> Route.delete(noinline body: suspend PipelineContext<Unit, ApplicationCall>.(T) -> Unit): Route {
    return location(T::class) {
        method(HttpMethod.Delete) {
            handle(body)
        }
    }
}

object Paths {
    /**
     * Get list of categories
     * 
     */
    @Location("/category") class getCategories()

    /**
     * Get list of random questions of category
     * 
     * @param category  
     */
    @Location("/quiz/{category}") class getQuiz(val category: kotlin.String)

    /**
     * List global scores
     * 
     */
    @Location("/score") class listGlobalScores()

}
