/**
* Community Quiz
* This is the server for my community quiz game
*
* OpenAPI spec version: 1.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package hu.bme.communityQuiz.server.models


/**
 * 
 * @param id 
 * @param category 
 * @param question 
 * @param rightAnswer 
 * @param wrongAnswer1 
 * @param wrongAnswer2 
 * @param wrongAnswer3 
 */
data class Question (
    val id: kotlin.String,
    val category: kotlin.String,
    val question: kotlin.String,
    val rightAnswer: kotlin.String,
    val wrongAnswer1: kotlin.String,
    val wrongAnswer2: kotlin.String,
    val wrongAnswer3: kotlin.String
) {

}

