/**
* Community Quiz
* This is the server for my community quiz game
*
* OpenAPI spec version: 1.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package hu.bme.communityQuiz.server.models

import java.math.BigDecimal
import java.util.*
import javax.persistence.*

@Entity
@NamedQueries(
    NamedQuery(
        name = "listScore",
        query = "FROM Score"
    )
)
@Table(name = "score")
/**
 * 
 * @param id 
 * @param category 
 * @param point 
 */
data class Score (
    @Id
    @Column(name="id", length = 255)
    val id: String = UUID.randomUUID().toString(),
    val category: String = "",
    val point: BigDecimal = BigDecimal(0)
) {

}

