/**
* Community Quiz
* This is the server for my community quiz game
*
* OpenAPI spec version: 1.0.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/
package hu.bme.communityQuiz.server.models


/**
 * 
 * @param id 
 * @param category 
 * @param point 
 */
data class Score (
    val id: kotlin.String,
    val category: kotlin.String,
    val point: java.math.BigDecimal
) {

}

